name: Java CI with Maven

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: 'Run tests'
    runs-on: ubuntu-latest

    steps:


      - name: Git clone
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Install Google Chrome
        run: |
            chmod +x ./scripts/InstallChrome.sh
            ./scripts/InstallChrome.sh

      - name: Maven test
        run: mvn clean test
        env:
          CI_RUN: true

